### PR TITLE
Sprint 5 Mass Fixes : #49, 48, 44

### LINKED ISSUE #44: Fix edge case where no plans exist.
- [ ] Make sure patient creation with no plans doesn't crash app.
- [ ] Make sure deletion of all plans doesn't crash app.

### LINKED ISSUE #48: Improve box field displays.
- [ ]  All multi-line fields look really odd as they start at their center. If possible, they should either be starting from the top-left or be growing as necessary.

### LINKED ISSUE #49: Fix step list.
- [ ] Step list should display one step per step. May need to modify current JSON parsing methods for plans.

### PR DESCRIPTION
**Pull request by arodriguezfebres**
fixes #49 , step list now parsing properly.
fixes #48 , box field displays.
fixes #44 , no plan edge case.

screenshot_1511823732
screenshot_1511822222

### CODE REVIEW

File: app/src/main/java/com/ad_revenue/damp/Plan_Screen.java [hunk 1]
```diff
@@ -30,8 +30,8 @@ protected void onCreate(Bundle savedInstanceState) {
 
         String[] steps = myJSON.getInternalPlanProperties(myContext, patientName, "Steps");
         int planNumber = getIntent().getIntExtra("indexInto", 0);
-        String[] stringSteps = steps[planNumber].split("\\\\r?\\\\n");
-
+//        String[] stringSteps = steps[planNumber].split("\r\n\n|\r\r|\n\n");
```
Comment (arodriguezfebres) [inline app/src/main/java/com/ad_revenue/damp/Plan_Screen.java]: Forgot to delete this comment.

File: app/src/main/java/com/ad_revenue/damp/Services/JSONService.java [hunk 2]
```diff
@@ -289,6 +289,9 @@ public void deletePlan(Context context, String patientName, int position) {
         try {
             JSONArray myJson;
             FileReader file = new FileReader(getPatientPlans(context, patientName));
+            if(!isPlansPresent(context, patientName)) {
+                return new String[]{"No plans created."};
```
Comment (arodriguezfebres) [inline app/src/main/java/com/ad_revenue/damp/Services/JSONService.java]: With no plans present, instead of attempting to load plans, it creates a field that says "No plans created."
